# Generated by Django 4.1.7 on 2023-07-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(max_length=100)),
                ('total_testCase', models.IntegerField()),
                ('passed_testCase', models.IntegerField()),
                ('failed_testCase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_testCase', models.IntegerField()),
                ('passed_testCase', models.IntegerField()),
                ('failed_testCase', models.IntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='sailytics.build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='versionn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='sailytics.version'),
        ),
    ]
