# Generated by Django 4.1.7 on 2023-07-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='versionn',
            new_name='version',
        ),
    ]
