# Generated by Django 4.1.7 on 2023-07-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailytics', '0002_rename_versionn_build_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='Scripts',
        ),
        migrations.RenameModel(
            old_name='Build',
            new_name='StmBuild',
        ),
    ]
