# Generated by Django 4.1.7 on 2023-08-03 06:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailytics', '0005_rename_failed_testcases_scripts_failed_testcase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('main', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failedScripts', to='sailytics.scripts')),
            ],
        ),
    ]
