# Generated by Django 4.1.7 on 2023-08-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailytics', '0006_failedscripts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scripts',
            new_name='Script',
        ),
        migrations.RenameModel(
            old_name='FailedScripts',
            new_name='ScriptTestInfo',
        ),
    ]
